services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "password"  
      MYSQL_DATABASE: "Parking"
    user: "0:0"
    volumes:
      - db_data:/var/lib/mysql
    command: --skip-name-resolve --innodb-flush-method=O_DIRECT --datadir=/var/lib/mysql
  backend:
    build:
      context: ./Django-backend-parking-lot
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    command: >
      sh -c "
        echo 'Waiting for MySQL...' &&
        while ! mysqladmin ping -h db -uroot -ppassword --silent; do
          sleep 1
        done &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
  frontend:
    build:
      context: ./parking-lot
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "5173:5173"
    restart: unless-stopped
    depends_on:
      - backend  
volumes:
  db_data:
