# Generated by Django 5.1.4 on 2024-12-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0002_alter_parkinghistory_lot_alter_prebookinghistory_lot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prebookinghistory',
            old_name='vehicle_num',
            new_name='vehicle_number',
        ),
    ]
